### ISSUE TITLE
Mod request : MalisisDoors

### ISSUE THREAD

**Issue by Darkstuffs** [PreludeCraft/PreludePack#15]
http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/2076338-malisisdoors-1-7-10-1-7-1-24-04-2015

Purely decorative mod

**Comment by NEXUS2345** [comment]
![vwmin](https://cloud.githubusercontent.com/assets/4030870/7760005/cc90ec98-000e-11e5-8700-8937565146f5.gif)
