### ISSUE TITLE
will and nexus both derping

### ISSUE THREAD

**Issue by BigD999** [PreludeCraft/PreludePack#21]
you 2 stop durping

**Comment by NEXUS2345** [comment]
*derping

**Comment by Willsr71** [comment]
You*

**Comment by NEXUS2345** [comment]
![20130915-190532](https://cloud.githubusercontent.com/assets/4030870/8045911/cdebe790-0e2e-11e5-9d65-e77f0adcbd31.jpg)

**Comment by NEXUS2345** [comment]
![a5asdag](https://cloud.githubusercontent.com/assets/4030870/8211172/901493f0-150d-11e5-9711-318d354450d7.gif)
